# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.7.0
  heroku: circleci/heroku@1.2.6
jobs:
  get-pipeline-values:
    machine: true
    resource_class: nokeefe/small-container
    steps:
      - run: echo "This is a command executed by Runner"
  build:
    working_directory: ~/circleci-web-app
    docker:
      - image: cimg/node:14.17.5
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: install babel
          command: sudo yarn add --dev babel-jest @babel/core @babel/preset-env
      - run:
          name: install jest
          command: sudo npm install --save-dev jest
      - run:
          name: install libraries for testing
          command: |
              sudo npm i @testing-library/jest-dom
              sudo npm i @testing-library/dom
      - run:
          name: test
          command: npm test

  deploy:
    docker:
      - image: cimg/node:14.17.5
    steps:
      - checkout
      - run:
          name: deploy main branch to heroku
          command: |
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main

workflows:
  heroku_deploy:
    jobs:
      - get-pipeline-values
      # - build
      # - heroku/deploy-via-git:
      #     requires:
      #       - build

      #     filters:
      #       branches:
      #         only: main
