# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    working_directory: ~/circleci-web-app
    docker:
      - image: cimg/node:14.17.5
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      # - run:
      #     name: install-npm yarn
      #     command: sudo npm install -g yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: install babel
          command: sudo yarn add --dev babel-jest @babel/core @babel/preset-env
      - run:
          name: install jest
          command: sudo npm install --save-dev jest
      - run:
          name: install libraries for testing
          command: |
              sudo npm i @testing-library/jest-dom
              sudo npm i @testing-library/dom
      - run:
          name: test
          command: jest
