# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

workflows:
  sample:
    jobs:
      steps:
        - run: npm install --global yarn
        - run: yarn add --dev babel-jest @babel/core @babel/preset-env
        - run: npm install --save-dev jest
        - run: npm i @testing-library/jest-dom
        - run: npm i @testing-library/dom
        - node/test:
            version: '14.17.5'
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
